const API='../../api';
let usuario=null,productos=[],proveedores=[],inventario=[],movimientos=[],pedidos=[],reportes=null,estadoScmActual=null,productoHistorialId=null;
const $=id=>document.getElementById(id);
const esc=v=>String(v??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#039;'}[c]));
const api=async(path,options={})=>{const r=await fetch(`${API}/${path}`,{credentials:'same-origin',headers:{'Content-Type':'application/json',...(options.headers||{})},...options});const t=await r.text();let d;try{d=t?JSON.parse(t):{}}catch{const e=new Error(`Respuesta no JSON: ${t.slice(0,160)}`);e.status=r.status;throw e}if(!r.ok){const e=new Error(d.error||`HTTP ${r.status}`);e.status=r.status;throw e}return d};
const subirImagenCurso=async(file)=>{const fd=new FormData();fd.append('imagen',file);const r=await fetch(`${API}/scm_imagen_curso.php`,{method:'POST',credentials:'same-origin',body:fd});const t=await r.text();let d;try{d=t?JSON.parse(t):{}}catch{throw new Error(`Respuesta no JSON al subir imagen: ${t.slice(0,160)}`)}if(!r.ok)throw new Error(d.error||`HTTP ${r.status}`);return d};
function initials(n=''){return n.split(/\s+/).filter(Boolean).slice(0,2).map(x=>x[0]).join('').toUpperCase()||'SC'}
function notice(id,msg,error=false){const e=$(id);if(!e)return;e.className=`notice ${error?'error':'success'}`;e.textContent=msg}
function toast(msg,type='success',detalle=''){const e=$('scmToast');if(!e)return;e.className=`scm-toast ${type} show`;e.innerHTML=`<strong>${esc(msg)}</strong>${detalle?`<div>${esc(detalle)}</div>`:''}`;clearTimeout(e._timer);e._timer=setTimeout(()=>{e.className='scm-toast'},5500)}
const catalogChannel=('BroadcastChannel' in window)?new BroadcastChannel('upskill-catalogo-cursos'):null;
function notificarCatalogoCursos(motivo='actualizacion'){const payload={type:'catalogo-actualizado',motivo,ts:Date.now()};try{catalogChannel?.postMessage(payload)}catch(_){}try{localStorage.setItem('upskillCatalogoCursosUpdated',String(payload.ts))}catch(_){}}
function confirmarScm(titulo,mensaje,confirmText='Confirmar'){return new Promise(resolve=>{const modal=$('confirmScmModal'),title=$('confirmScmTitle'),text=$('confirmScmText'),ok=$('confirmScmAccept'),cancel=$('confirmScmCancel');if(!modal||!title||!text||!ok||!cancel){resolve(false);return}title.textContent=titulo;text.textContent=mensaje;ok.textContent=confirmText;modal.classList.add('open');const cerrarConfirm=(resultado)=>{modal.classList.remove('open');ok.onclick=null;cancel.onclick=null;resolve(resultado)};ok.onclick=()=>cerrarConfirm(true);cancel.onclick=()=>cerrarConfirm(false)})}
function abrir(id){$(id)?.classList.add('open')}function cerrar(id){$(id)?.classList.remove('open')}
function ahora(){return new Date(Date.now()-new Date().getTimezoneOffset()*60000).toISOString().slice(0,16)}
function scmImageUrl(path=''){const v=String(path||'').trim();if(!v)return '../../src/primer.jpg';if(/^https?:\/\//i.test(v)||v.startsWith('data:'))return v;const clean=v.replace(/^\.\.\/src\//,'').replace(/^src\//,'').replace(/^\.\.\//,'');return '../../src/'+clean}
function nivelDesdePorcentaje(v){v=Number(v)||0;return v>=67?'Optimizado':v>=34?'En desarrollo':'Inicial'}
function cambiarSeccion(id){document.querySelectorAll('.section').forEach(s=>s.classList.toggle('active',s.id===id));document.querySelectorAll('.scm-nav button[data-section]').forEach(b=>b.classList.toggle('active',b.dataset.section===id));const t={inicio:'SCM',productos:'Cursos',proveedores:'Proveedores',inventario:'Inventario de licencias',movimientos:'Movimientos de licencias',logistica:'Logística — Push / Pull',pedidos:'Pedidos',madurez:'Nivel de madurez SCM',reportes:'Reportes SCM'};$('pageTitle').textContent=t[id]||'SCM';if(id==='reportes')cargarReportes();if(id==='madurez')cargarEstadoScm()}

async function iniciar(){
  try{
    const me=await api('me.php');usuario=me.usuario;
    if(!usuario||!['admin','logistica'].includes(usuario.rol)){window.location.replace('../pagPrin.html');return}
    const esLog=usuario.rol==='logistica';
    $('userInfo').textContent=`${usuario.nombre} · ${esLog?'logística':'administrador'}`;$('adminName').textContent=usuario.nombre;$('adminInitials').textContent=initials(usuario.nombre);$('adminRole').textContent=esLog?'Logística':'Admin';$('scmRoleBrand').textContent=esLog?'SCM · Logística':'SCM · Administrador';
    if(esLog){$('crmBtn').hidden=true;$('adminPanelBtn').hidden=true}
    await Promise.all([cargarProveedores(),cargarProductos()]);
    await Promise.all([cargarInventario(),cargarMovimientos(),cargarPedidos(),cargarReportes(),cargarEstadoScm()]);
  }catch(e){
    if(e.status===401||e.status===403){window.location.replace('../CMR/Administradores/loggin.html');return}
    toast('No fue posible cargar el SCM','error',e.message);
  }
}
async function obtenerUsuarioActual(){
  const me=await api('me.php');
  usuario=me.usuario||null;
  return usuario;
}
async function validarSesionAlVolver(){
  try{
    const actual=await obtenerUsuarioActual();
    if(!actual||!['admin','logistica'].includes(actual.rol))window.location.replace('../CMR/Administradores/loggin.html');
  }catch(e){
    if(e.status===401||e.status===403)window.location.replace('../CMR/Administradores/loggin.html');
    else toast('No fue posible validar la sesión','error',e.message);
  }
}
async function irSegunRol(destinoAdmin,destinoLogistica=null){
  try{
    const actual=await obtenerUsuarioActual();
    if(actual?.rol==='admin'){window.location.href=destinoAdmin;return}
    if(actual?.rol==='logistica'&&destinoLogistica){window.location.href=destinoLogistica;return}
    if(actual?.rol==='logistica'){toast('Acceso restringido','error','Los usuarios de logística no pueden acceder a esta sección.');return}
    window.location.replace('../CMR/Administradores/loggin.html');
  }catch(e){
    if(e.status===401||e.status===403)window.location.replace('../CMR/Administradores/loggin.html');
    else toast('No fue posible validar la sesión','error',e.message);
  }
}

// ===== CURSOS / PRODUCTOS =====
async function cargarProductos(){const d=await api('scm_productos.php');productos=d.productos||[];renderProductos();llenarSelects();renderEstrategias()}
function renderProductos(){
  const q=$('buscarProducto').value.toLowerCase().trim(),cat=$('filtroCategoria').value;
  const cats=[...new Set(productos.map(p=>p.categoria))].sort(),cur=$('filtroCategoria').value;
  $('filtroCategoria').innerHTML='<option value="">Todas las categorías</option>'+cats.map(c=>`<option ${c===cur?'selected':''}>${esc(c)}</option>`).join('');
  const lista=productos.filter(p=>(!q||[p.nombre,p.categoria,p.proveedor_nombre,p.nivel,p.tags].some(v=>String(v??'').toLowerCase().includes(q)))&&(!cat||p.categoria===cat));
  $('productosBody').innerHTML=lista.length?lista.map(p=>`<tr><td>${p.id}</td><td><img class="course-thumb" src="${esc(scmImageUrl(p.imagen))}" alt="${esc(p.nombre)}" onerror="this.src='../../src/primer.jpg'"></td><td>${esc(p.nombre)}</td><td>${esc(p.categoria)}</td><td>${p.stock_actual}</td><td>${p.stock_minimo}</td><td>${esc(p.proveedor_nombre||'—')}</td><td><button class="action strategy strategy-product" data-id="${p.id}" title="Cambiar estrategia">${esc(p.estrategia_logistica)} ⇄</button></td><td><button class="action view view-product" data-id="${p.id}" title="Ver">👁</button><button class="action edit edit-product" data-id="${p.id}" title="Editar">✎</button><button class="action delete delete-product" data-id="${p.id}" title="Dar de baja">🗑</button></td></tr>`).join(''):'<tr><td colspan="9">Sin cursos.</td></tr>'
}
function llenarSelects(){const opts=productos.map(p=>`<option value="${p.id}">${esc(p.nombre)}</option>`).join('');['movimientoProducto','pedidoProducto','estrategiaProducto'].forEach(id=>{$(id).innerHTML=opts||'<option value="">Sin cursos</option>'});const popts='<option value="">Selecciona proveedor</option>'+proveedores.map(p=>`<option value="${p.id}">${esc(p.nombre)}</option>`).join('');$('productoProveedor').innerHTML=popts;$('pedidoProveedor').innerHTML=popts;$('filtroMovimientoProducto').innerHTML='<option value="">Todos los cursos</option>'+opts}
function resetProducto(proveedorId=''){$('productoForm').reset();$('productoId').value='';$('productoUnidad').value='Licencia';$('productoModalTitle').textContent='Nuevo curso SCM';$('productoProveedor').value=proveedorId||'';$('productoImagenActual').value='';$('productoImagenPreview').src='../../src/primer.jpg'}
async function guardarProducto(e){
  e.preventDefault();
  const id=$('productoId').value;
  const nivel=$('productoNivel').value.trim(),duracion=$('productoDuracion').value.trim(),fecha=$('productoFechaPublicacion').value,descuentoRaw=$('productoDescuento').value,proveedor=Number($('productoProveedor').value||0);
  if(!nivel)return notice('productoNotice','El nivel es obligatorio.',true);
  if(!duracion)return notice('productoNotice','La duración es obligatoria.',true);
  if(!fecha)return notice('productoNotice','La fecha de publicación es obligatoria.',true);
  if(descuentoRaw==='')return notice('productoNotice','El descuento es obligatorio. Usa 0 si no aplica.',true);
  if(!proveedor)return notice('productoNotice','Debes seleccionar un proveedor.',true);
  try{
    let imagen=$('productoImagenActual').value.trim();
    const archivo=$('productoImagenArchivo').files?.[0];
    if(archivo){const up=await subirImagenCurso(archivo);imagen=up.imagen;$('productoImagenActual').value=imagen;}
    const p={nombre:$('productoNombre').value.trim(),descripcion:$('productoDescripcion').value.trim(),categoria:$('productoCategoria').value.trim(),nivel,duracion,valoracion:Number($('productoValoracion').value||0),tags:$('productoTags').value.trim(),descuento:Number(descuentoRaw),fecha_publicacion:fecha,imagen,precio_venta:Number($('productoPrecio').value||0),proveedor_id:proveedor,stock_actual:Number($('productoStock').value),stock_minimo:Number($('productoMin').value),unidad_inventario:'Licencia',estrategia_logistica:$('productoEstrategia').value,costo_unitario:Number($('productoCosto').value)};
    const d=await api(`scm_productos.php${id?`?id=${id}`:''}`,{method:id?'PUT':'POST',body:JSON.stringify(p)});
    cerrar('productoModal');
    if(d.movimiento){toast(`Inventario actualizado: ${String(d.movimiento.tipo).toUpperCase()}`,'success',`${d.movimiento.cantidad} licencia(s). ${d.movimiento.descripcion}${d.pedido_push_generado?' · Se generó y surtió la reposición PUSH automáticamente.':''}`)}else{toast(id?'Curso actualizado':'Curso dado de alta','success',d.mensaje||p.nombre)}
    await Promise.all([cargarProductos(),cargarInventario(),cargarMovimientos(),cargarPedidos(),cargarReportes(),cargarEstadoScm()]);
    notificarCatalogoCursos(id?'curso-editado':'curso-creado');
  }catch(err){notice('productoNotice',err.message,true)}
}
function editarProducto(id){const p=productos.find(x=>Number(x.id)===Number(id));if(!p)return;$('productoForm').reset();$('productoId').value=p.id;$('productoModalTitle').textContent='Editar curso SCM';$('productoNombre').value=p.nombre;$('productoDescripcion').value=p.descripcion||'';$('productoCategoria').value=p.categoria;$('productoNivel').value=p.nivel||'';$('productoDuracion').value=p.duracion||'';$('productoValoracion').value=p.valoracion||0;$('productoTags').value=p.tags||'';$('productoDescuento').value=p.descuento??0;$('productoFechaPublicacion').value=p.fecha_publicacion||'';$('productoImagenActual').value=p.imagen||'';$('productoImagenArchivo').value='';$('productoImagenPreview').src=scmImageUrl(p.imagen);$('productoPrecio').value=p.precio_venta||0;$('productoProveedor').value=p.proveedor_id||'';$('productoStock').value=p.stock_actual;$('productoMin').value=p.stock_minimo;$('productoUnidad').value=p.unidad_inventario||'Licencia';$('productoEstrategia').value=p.estrategia_logistica;$('productoCosto').value=p.costo_unitario;abrir('productoModal')}
function verProducto(id){const p=productos.find(x=>Number(x.id)===Number(id));if(!p)return;$('productoDetalleContenido').innerHTML=`<div class="course-detail-image-wrap"><img class="course-detail-image" src="${esc(scmImageUrl(p.imagen))}" alt="${esc(p.nombre)}" onerror="this.src='../../src/primer.jpg'"></div><div class="details-grid"><div class="key">Curso</div><div class="value">${esc(p.nombre)}</div><div class="key">Categoría</div><div>${esc(p.categoria)}</div><div class="key">Nivel</div><div>${esc(p.nivel||'—')}</div><div class="key">Proveedor</div><div>${esc(p.proveedor_nombre||'Sin proveedor')}</div><div class="key">Precio</div><div>$${Number(p.precio_venta||0).toFixed(2)}</div><div class="key">Costo licencia</div><div>$${Number(p.costo_unitario||0).toFixed(2)}</div><div class="key">Licencias</div><div>${p.stock_actual} disponibles / mínimo ${p.stock_minimo}</div><div class="key">Estrategia</div><div>${esc(p.estrategia_logistica)}</div><div class="key">Descripción</div><div>${esc(p.descripcion||'—')}</div></div>`;abrir('productoDetalleModal')}
async function borrarProducto(id){const confirmado=await confirmarScm('Dar de baja curso','¿Dar de baja lógicamente este curso? El registro permanecerá en la base de datos.','Dar de baja');if(!confirmado)return;try{const d=await api(`scm_productos.php?id=${id}`,{method:'DELETE'});toast('Curso dado de baja','info',d.mensaje);await Promise.all([cargarProductos(),cargarInventario(),cargarEstadoScm(),cargarReportes()]);notificarCatalogoCursos('curso-baja-logica')}catch(e){toast('No fue posible dar de baja el curso','error',e.message)}}
function irAEstrategia(id){cambiarSeccion('logistica');$('estrategiaProducto').value=id;renderEstrategias();$('configurarEstrategiaPanel')?.scrollIntoView({behavior:'smooth',block:'start'})}

// ===== PROVEEDORES =====
async function cargarProveedores(){const d=await api('scm_proveedores.php');proveedores=d.proveedores||[];renderProveedores();llenarSelects()}
function renderProveedores(){const q=$('buscarProveedor').value.toLowerCase().trim();const lista=proveedores.filter(p=>!q||[p.nombre,p.contacto,p.correo,p.telefono].some(v=>String(v??'').toLowerCase().includes(q)));$('proveedoresBody').innerHTML=lista.length?lista.map(p=>`<tr><td>${p.id}</td><td>${esc(p.nombre)}</td><td>${esc(p.contacto)}</td><td>${esc(p.correo)}</td><td>${esc(p.telefono)}</td><td><button class="action view view-provider" data-id="${p.id}" title="Ver">👁</button><button class="action add-course provider-course" data-id="${p.id}" title="Dar de alta curso con este proveedor">+ Curso</button><button class="action edit edit-provider" data-id="${p.id}" title="Editar">✎</button><button class="action delete delete-provider" data-id="${p.id}" title="Desactivar">🗑</button></td></tr>`).join(''):'<tr><td colspan="6">Sin proveedores.</td></tr>'}
async function guardarProveedor(e){e.preventDefault();const id=$('proveedorId').value;const p={nombre:$('proveedorNombre').value.trim(),contacto:$('proveedorContacto').value.trim(),correo:$('proveedorCorreo').value.trim(),telefono:$('proveedorTelefono').value.trim(),direccion:$('proveedorDireccion').value.trim()};if(!p.direccion)return notice('proveedorNotice','La dirección es obligatoria.',true);try{const d=await api(`scm_proveedores.php${id?`?id=${id}`:''}`,{method:id?'PUT':'POST',body:JSON.stringify(p)});cerrar('proveedorModal');toast(id?'Proveedor actualizado':'Proveedor dado de alta','success',d.mensaje);await Promise.all([cargarProveedores(),cargarProductos(),cargarEstadoScm()]);notificarCatalogoCursos(id?'proveedor-editado':'proveedor-creado')}catch(err){notice('proveedorNotice',err.message,true)}}
function editarProveedor(id){const p=proveedores.find(x=>Number(x.id)===Number(id));if(!p)return;$('proveedorId').value=p.id;$('proveedorModalTitle').textContent='Editar proveedor';$('proveedorNombre').value=p.nombre;$('proveedorContacto').value=p.contacto;$('proveedorCorreo').value=p.correo;$('proveedorTelefono').value=p.telefono;$('proveedorDireccion').value=p.direccion||'';abrir('proveedorModal')}
function verProveedor(id){const p=proveedores.find(x=>Number(x.id)===Number(id));if(!p)return;const cursos=productos.filter(x=>Number(x.proveedor_id)===Number(id));$('proveedorDetalleContenido').innerHTML=`<div class="details-grid"><div class="key">Proveedor</div><div>${esc(p.nombre)}</div><div class="key">Contacto</div><div>${esc(p.contacto)}</div><div class="key">Correo</div><div>${esc(p.correo)}</div><div class="key">Teléfono</div><div>${esc(p.telefono)}</div><div class="key">Dirección</div><div>${esc(p.direccion||'—')}</div><div class="key">Cursos asociados</div><div>${cursos.length?cursos.map(c=>esc(c.nombre)).join(', '):'Sin cursos asociados'}</div></div>`;abrir('proveedorDetalleModal')}
async function borrarProveedor(id){const confirmado=await confirmarScm('Desactivar proveedor','¿Desactivar este proveedor? Sus cursos conservarán la referencia histórica.','Desactivar');if(!confirmado)return;try{const d=await api(`scm_proveedores.php?id=${id}`,{method:'DELETE'});toast('Proveedor desactivado','info',d.mensaje);await Promise.all([cargarProveedores(),cargarProductos(),cargarEstadoScm()]);notificarCatalogoCursos('proveedor-desactivado')}catch(e){toast('No fue posible desactivar el proveedor','error',e.message)}}
function nuevoCursoParaProveedor(id){resetProducto(String(id));abrir('productoModal')}

// ===== INVENTARIO E HISTORIAL =====
async function cargarInventario(){const d=await api('scm_inventario.php');inventario=d.inventario||[];renderInventario()}
function renderInventario(){const q=$('buscarInventario').value.toLowerCase().trim();const lista=inventario.filter(x=>!q||String(x.producto).toLowerCase().includes(q));$('inventarioBody').innerHTML=lista.length?lista.map(x=>`<tr><td>${esc(x.producto)}</td><td>${x.stock_actual}</td><td>${x.stock_minimo}</td><td><span class="badge ${x.estado_stock==='Pocas licencias'||x.estado_stock==='Licencias bajas'||x.estado_stock==='Stock bajo'?'low':'ok'}">${esc(x.estado_stock)}</span></td><td><span class="badge ${x.estrategia_logistica.toLowerCase()}">${x.estrategia_logistica}</span></td><td><button class="action view inv-history" data-id="${x.producto_id}" title="Ver historia del inventario">👁 Historial</button></td></tr>`).join(''):'<tr><td colspan="6">Sin inventario.</td></tr>'}
async function cargarMovimientos(){const tipo=$('filtroMovimientoTipo').value,prod=$('filtroMovimientoProducto').value;const qs=new URLSearchParams();if(tipo)qs.set('tipo',tipo);if(prod)qs.set('producto_id',prod);const d=await api(`scm_movimientos.php${qs.toString()?`?${qs}`:''}`);movimientos=d.movimientos||[];$('movimientosBody').innerHTML=movimientos.length?movimientos.map(m=>`<tr><td>${esc(m.fecha)}</td><td>${esc(m.producto)}</td><td><span class="badge ${m.tipo==='entrada'?'ok':'low'}">${esc(m.tipo)}</span></td><td>${m.cantidad}</td><td>${esc(m.motivo)}</td><td>${esc(m.usuario)}</td></tr>`).join(''):'<tr><td colspan="6">Sin movimientos.</td></tr>'}
async function verHistorialInventario(id){productoHistorialId=Number(id);const p=productos.find(x=>Number(x.id)===Number(id));const d=await api(`scm_movimientos.php?producto_id=${id}`);const rows=d.movimientos||[];$('historialInventarioTitle').textContent=`Historia de inventario — ${p?.nombre||'Curso'}`;$('historialInventarioBody').innerHTML=rows.length?rows.map(m=>`<tr><td>${esc(m.fecha)}</td><td><span class="badge ${m.tipo==='entrada'?'ok':'low'}">${esc(m.tipo)}</span></td><td>${m.cantidad}</td><td>${esc(m.motivo)}</td><td>${esc(m.detalle||'—')}</td><td>${esc(m.usuario)}</td></tr>`).join(''):'<tr><td colspan="6">Este curso aún no tiene movimientos.</td></tr>';abrir('historialInventarioModal')}
async function guardarMovimiento(e){e.preventDefault();const p={producto_id:Number($('movimientoProducto').value),tipo:$('movimientoTipo').value,cantidad:Number($('movimientoCantidad').value),motivo:$('movimientoMotivo').value,fecha:$('movimientoFecha').value,detalle:$('movimientoDetalle').value.trim()};if(!p.detalle){notice('movimientoNotice','El detalle del movimiento es obligatorio.',true);return}try{const d=await api('scm_movimientos.php',{method:'POST',body:JSON.stringify(p)});cerrar('movimientoModal');const m=d.movimiento||{};toast(`Movimiento ${String(m.tipo||p.tipo).toUpperCase()} registrado`,'success',`${m.curso||''}: ${m.cantidad||p.cantidad} licencia(s). ${m.descripcion||p.detalle||m.motivo||p.motivo}${d.pedido_push_generado?' · Se generó y surtió la reposición PUSH automáticamente.':''}`);await Promise.all([cargarProductos(),cargarInventario(),cargarMovimientos(),cargarPedidos(),cargarReportes()]);if(productoHistorialId===p.producto_id&&$('historialInventarioModal').classList.contains('open'))await verHistorialInventario(p.producto_id);notificarCatalogoCursos('movimiento-inventario')}catch(err){notice('movimientoNotice',err.message,true);toast('Movimiento no registrado','error',err.message)}}

// ===== ESTRATEGIAS =====
function renderEstrategias(){const pushList=productos.filter(p=>p.estrategia_logistica==='PUSH'),pullList=productos.filter(p=>p.estrategia_logistica==='PULL'),push=pushList.length,pull=pullList.length;$('pushCount').textContent=`${push} cursos`;$('pullCount').textContent=`${pull} cursos`;$('estrategiaBody').innerHTML=productos.length?productos.map(p=>`<tr><td>${esc(p.nombre)}</td><td>${esc(p.categoria)}</td><td>${p.stock_actual}</td><td>${p.stock_minimo}</td><td><span class="badge ${p.estrategia_logistica.toLowerCase()}">${p.estrategia_logistica}</span></td><td><button class="action strategy strategy-row" data-id="${p.id}">Cambiar</button></td></tr>`).join(''):'<tr><td colspan="6">Sin cursos.</td></tr>';const max=Math.max(push,pull,1);$('strategyChart').innerHTML=`<div class="strategy-chart-row"><b>PUSH</b><div class="strategy-chart-track"><div class="strategy-chart-fill push" style="width:${Math.round(push/max*100)}%"></div></div><strong>${push}</strong></div><div class="strategy-chart-row"><b>PULL</b><div class="strategy-chart-track"><div class="strategy-chart-fill pull" style="width:${Math.round(pull/max*100)}%"></div></div><strong>${pull}</strong></div><div class="strategy-product-list"><div><b>Cursos PUSH</b><ul>${pushList.map(p=>`<li>${esc(p.nombre)}</li>`).join('')||'<li>Ninguno</li>'}</ul></div><div><b>Cursos PULL</b><ul>${pullList.map(p=>`<li>${esc(p.nombre)}</li>`).join('')||'<li>Ninguno</li>'}</ul></div></div>`;const id=Number($('estrategiaProducto').value);const p=productos.find(x=>Number(x.id)===id)||productos[0];if(p){$('estrategiaProducto').value=p.id;const radio=document.querySelector(`input[name="estrategia"][value="${p.estrategia_logistica}"]`);if(radio)radio.checked=true}}
function setStrategyMode(mode){document.querySelectorAll('.strategy-mode').forEach(b=>{const on=b.dataset.strategyMode===mode;b.classList.toggle('active',on);b.classList.toggle('primary',on);b.classList.toggle('secondary',!on)});$('strategyTableView').classList.toggle('active',mode==='table');$('strategyChartView').classList.toggle('active',mode==='chart')}
async function guardarEstrategia(){const id=Number($('estrategiaProducto').value),est=document.querySelector('input[name="estrategia"]:checked')?.value;if(!id||!est)return;try{const d=await api('scm_estrategia.php',{method:'PUT',body:JSON.stringify({id,estrategia_logistica:est})});notice('estrategiaNotice',d.mensaje+(d.pedido_push_generado?' Se generó y surtió automáticamente la reposición PUSH de licencias.':''));toast('Estrategia actualizada','success',`${productos.find(p=>Number(p.id)===id)?.nombre||'Curso'} ahora usa ${est}.${d.pedido_push_generado?' La reposición PUSH se creó y surtió automáticamente.':''}`);await Promise.all([cargarProductos(),cargarPedidos(),cargarReportes()]);notificarCatalogoCursos('estrategia-actualizada')}catch(e){notice('estrategiaNotice',e.message,true);toast('No se pudo cambiar la estrategia','error',e.message)}}

// ===== PEDIDOS =====
async function cargarPedidos(){const estado=$('filtroPedidoEstado').value,tipo=$('filtroPedidoTipo').value;const qs=new URLSearchParams();if(estado)qs.set('estado',estado);if(tipo)qs.set('tipo',tipo);const d=await api(`scm_pedidos.php${qs.toString()?`?${qs}`:''}`);pedidos=d.pedidos||[];$('pedidosBody').innerHTML=pedidos.length?pedidos.map(p=>`<tr><td>${esc(p.folio)}</td><td>${esc(p.fecha)}</td><td>${esc(p.producto)}</td><td>${esc(p.proveedor||'—')}</td><td>${p.cantidad}</td><td>${esc(p.tipo)}</td><td><span class="badge ${String(p.estrategia_origen||p.estrategia_actual||'PULL').toLowerCase()}">${esc(p.estrategia_origen||p.estrategia_actual||'PULL')}</span></td><td><span class="badge">${esc(p.estado)}</span></td><td>${esc(p.origen)}</td><td><select class="pedido-estado" data-id="${p.id}"><option ${p.estado==='pendiente'?'selected':''}>pendiente</option><option ${p.estado==='en_proceso'?'selected':''}>en_proceso</option><option ${p.estado==='surtido'?'selected':''}>surtido</option><option ${p.estado==='cancelado'?'selected':''}>cancelado</option></select></td></tr>`).join(''):'<tr><td colspan="10">Sin pedidos.</td></tr>';const pull=pedidos.filter(p=>(p.estrategia_origen||p.estrategia_actual)==='PULL');$('pullPedidosBody').innerHTML=pull.length?pull.map(p=>`<tr><td>${esc(p.folio)}</td><td>${esc(p.producto)}</td><td>${esc(p.proveedor||'—')}</td><td>${esc(p.tipo)}</td><td>${esc(p.estado)}</td><td>${esc(p.fecha)}</td></tr>`).join(''):'<tr><td colspan="6">No hay pedidos PULL en este filtro.</td></tr>'}
async function guardarPedido(e){e.preventDefault();const p={producto_id:Number($('pedidoProducto').value),cantidad:Number($('pedidoCantidad').value),tipo:$('pedidoTipo').value,proveedor_id:Number($('pedidoProveedor').value||0),fecha:$('pedidoFecha').value,notas:$('pedidoNotas').value.trim()};if(!p.proveedor_id){notice('pedidoNotice','Selecciona un proveedor para el pedido.',true);return}try{const d=await api('scm_pedidos.php',{method:'POST',body:JSON.stringify(p)});cerrar('pedidoModal');toast('Pedido registrado','success',`${d.folio||''} · Estrategia ${d.estrategia_origen||''}`);await Promise.all([cargarPedidos(),cargarReportes()]);notificarCatalogoCursos('pedido-creado')}catch(err){notice('pedidoNotice',err.message,true);toast('Pedido no registrado','error',err.message)}}
async function cambiarEstadoPedido(id,estado){try{const d=await api(`scm_pedidos.php?id=${id}`,{method:'PUT',body:JSON.stringify({estado})});if(d.movimiento){toast(`Inventario actualizado: ${String(d.movimiento.tipo).toUpperCase()}`,'success',`${d.movimiento.cantidad} licencia(s). ${d.movimiento.descripcion}`)}else toast('Pedido actualizado','success',d.mensaje);await Promise.all([cargarPedidos(),cargarProductos(),cargarInventario(),cargarMovimientos(),cargarReportes()]);notificarCatalogoCursos('pedido-actualizado')}catch(e){toast('No se pudo actualizar el pedido','error',e.message);await cargarPedidos()}}

// ===== MADUREZ MANUAL =====
function pintarMadurez(valor){valor=Math.max(0,Math.min(100,Number(valor)||0));const nivel=nivelDesdePorcentaje(valor);$('nivelActualLabel').textContent=nivel;$('nivelActualPercent').textContent=`${valor}%`;$('nivelScmRange').style.background=`linear-gradient(90deg,#cfead8 0%,#78c69a ${Math.min(valor,55)}%,#176b45 ${valor}%,#e5ece8 ${valor}%,#e5ece8 100%)`;document.querySelectorAll('.maturity-level-card').forEach(card=>card.classList.toggle('active',card.dataset.level===nivel))}
const checklistLabels={productos_proveedores:['Productos y proveedores integrados','Cursos y proveedores están relacionados y pueden gestionarse.'],inventario:['Inventario funcionando','Licencias/membresías con estado Normal o Pocas licencias.'],trazabilidad:['Trazabilidad de movimientos','Entradas y salidas registran motivo, fecha y usuario.'],push_pull:['Estrategia PUSH/PULL implementada','La logística puede configurarse por curso.'],reportes:['Reportes y métricas','La información puede revisarse en tablas y gráficas.']};
function actualizarProgresoChecklist(){const checks=[...document.querySelectorAll('.scm-check')];const n=checks.filter(x=>x.checked).length,total=checks.length||5,pct=Math.round(n/total*100);$('checkProgressText').textContent=`${n}/${total}`;$('checkProgressPercent').textContent=`${pct}%`;checks.forEach(c=>c.closest('.checkitem')?.classList.toggle('checked',c.checked))}
async function cargarEstadoScm(){try{const d=await api('scm_estado.php');estadoScmActual=d;const pct=Number(d.estado?.nivel_porcentaje??0);$('nivelScmRange').value=pct;$('nivelDescripcion').value=d.estado?.descripcion||'';pintarMadurez(pct);const conteos=d.conteos||{};const detalles={productos_proveedores:`Evidencia actual: ${conteos.productos||0} cursos y ${conteos.proveedores||0} proveedores.`,inventario:`Evidencia actual: ${conteos.inventario||0} cursos administrados como licencias.`,trazabilidad:`Evidencia actual: ${conteos.movimientos||0} movimientos registrados.`,push_pull:`Evidencia actual: PUSH ${conteos.push||0} · PULL ${conteos.pull||0}.`,reportes:`Evidencia actual: ${conteos.pedidos||0} pedidos registrados.`};$('checklistScm').innerHTML=Object.entries(checklistLabels).map(([k,v])=>`<label class="checkitem manual ${d.checklist?.[k]?'checked':''}"><input class="scm-check" type="checkbox" data-key="${k}" ${d.checklist?.[k]?'checked':''}><div><strong>${esc(v[0])}</strong><span class="check-detail">${esc(v[1])}</span><span class="check-detail">${esc(detalles[k])}</span></div></label>`).join('');document.querySelectorAll('.scm-check').forEach(c=>c.onchange=actualizarProgresoChecklist);actualizarProgresoChecklist()}catch(e){notice('nivelNotice',e.message,true)}}
async function guardarNivel(){try{const checklist={};document.querySelectorAll('.scm-check').forEach(c=>checklist[c.dataset.key]=c.checked);const porcentaje=Number($('nivelScmRange').value);const d=await api('scm_estado.php',{method:'PUT',body:JSON.stringify({nivel_porcentaje:porcentaje,descripcion:$('nivelDescripcion').value.trim(),checklist})});pintarMadurez(d.nivel_porcentaje);actualizarProgresoChecklist();notice('nivelNotice',`${d.mensaje} Nivel: ${d.nivel_scm} (${d.nivel_porcentaje}%).`);toast('Progreso SCM guardado','success','El checklist y el nivel de madurez quedaron registrados para la exposición.')}catch(e){notice('nivelNotice',e.message,true)}}

// ===== REPORTES =====
function setReportMode(mode){document.querySelectorAll('.report-mode').forEach(b=>{const on=b.dataset.reportMode===mode;b.classList.toggle('active',on);b.classList.toggle('primary',on);b.classList.toggle('secondary',!on)});$('reportChartsView').classList.toggle('active',mode==='charts');$('reportTablesView').classList.toggle('active',mode==='tables')}
async function cargarReportes(){try{const d=await api('scm_reportes.php');reportes=d;const r=d.resumen||{};$('rProductos').textContent=r.productos||0;$('rProveedores').textContent=r.proveedores||0;$('rPedidos').textContent=r.pedidos_proceso||0;$('rStockBajo').textContent=r.stock_bajo||0;const ventas=d.productos_mas_vendidos||[],pp=d.push_pull||[],crit=d.inventario_critico||[],rot=d.rotacion_lenta||[];renderBars('ventasChart',ventas.map(x=>({label:x.nombre,value:Number(x.total_asignado||0)})));renderDonutPushPull(pp);renderCriticalVertical(crit);renderBars('rotacionChart',rot.slice(0,8).map(x=>({label:x.nombre,value:Number(x.stock_actual||0)})));$('ventasBody').innerHTML=ventas.map(x=>`<tr><td>${esc(x.nombre)}</td><td>${Number(x.total_asignado||0)}</td></tr>`).join('')||'<tr><td colspan="2">Sin asignaciones registradas.</td></tr>';$('pushPullBody').innerHTML=pp.map(x=>`<tr><td>${esc(x.estrategia)}</td><td>${Number(x.total||0)}</td></tr>`).join('')||'<tr><td colspan="2">Sin datos.</td></tr>';$('criticoBody').innerHTML=crit.map(x=>`<tr><td>${esc(x.nombre)}</td><td>${x.stock_actual}</td><td>${x.stock_minimo}</td><td>${esc(x.estrategia_logistica)}</td></tr>`).join('')||'<tr><td colspan="4">Sin licencias críticas.</td></tr>';$('rotacionBody').innerHTML=rot.map(x=>`<tr><td>${esc(x.nombre)}</td><td>${x.stock_actual}</td><td>${esc(x.ultima_salida||'Sin salidas registradas')}</td></tr>`).join('')||'<tr><td colspan="3">Sin datos.</td></tr>'}catch(e){toast('No fue posible cargar reportes','error',e.message)}}
function renderBars(id,items){const max=Math.max(1,...items.map(x=>x.value));$(id).innerHTML=items.length?items.map(x=>`<div class="bar-row"><span>${esc(x.label)}</span><div class="bar-track"><div class="bar-fill" style="width:${Math.round(x.value/max*100)}%"></div></div><b>${x.value}</b></div>`).join(''):'<div class="small">Sin datos.</div>'}
function renderDonutPushPull(items){const push=Number(items.find(x=>x.estrategia==='PUSH')?.total||0),pull=Number(items.find(x=>x.estrategia==='PULL')?.total||0),total=push+pull||1,pct=Math.round(push/total*100),angle=Math.round(push/total*360);$('pushPullDonut').innerHTML=`<div class="donut" style="--push-angle:${angle}deg"><div class="donut-center">${pct}%</div></div><div class="donut-legend"><div class="legend-item"><span class="legend-dot" style="background:#176b45"></span>PUSH: <strong>${push}</strong></div><div class="legend-item"><span class="legend-dot" style="background:#4f8ad0"></span>PULL: <strong>${pull}</strong></div></div>`}
function renderCriticalVertical(items){const max=Math.max(1,...items.map(x=>Number(x.stock_minimo||0)));$('criticoChart').innerHTML=items.length?items.slice(0,10).map(x=>{const val=Number(x.stock_actual||0),h=Math.max(6,Math.round(val/max*100));return `<div class="vbar-item"><span class="vbar-value">${val}/${x.stock_minimo}</span><div class="vbar-track"><div class="vbar-fill" style="height:${h}%"></div></div><span class="vbar-label">${esc(x.nombre)}</span></div>`}).join(''):'<div class="small">No hay cursos con licencias críticas.</div>'}

function globalSearch(){const q=$('globalSearch').value.toLowerCase().trim();const active=document.querySelector('.section.active')?.id;if(active==='productos'){$('buscarProducto').value=q;renderProductos()}else if(active==='proveedores'){$('buscarProveedor').value=q;renderProveedores()}else if(active==='inventario'){$('buscarInventario').value=q;renderInventario()}}
function toggleTheme(){document.body.classList.toggle('dark-mode');localStorage.setItem('upskillTheme',document.body.classList.contains('dark-mode')?'dark':'light');$('themeBtn').textContent=document.body.classList.contains('dark-mode')?'☀':'☾'}
function toggleLanguage(){const lang=document.documentElement.dataset.language==='es'?'en':'es';document.documentElement.dataset.language=lang;$('languageBtn').textContent=lang==='es'?'ES':'EN';localStorage.setItem('upskillLanguage',lang)}

document.addEventListener('DOMContentLoaded',()=>{
  if(localStorage.getItem('upskillTheme')==='dark')document.body.classList.add('dark-mode');document.documentElement.dataset.language=localStorage.getItem('upskillLanguage')||'es';$('themeBtn').textContent=document.body.classList.contains('dark-mode')?'☀':'☾';$('languageBtn').textContent=document.documentElement.dataset.language==='es'?'ES':'EN';
  document.querySelectorAll('.scm-nav button[data-section]').forEach(b=>b.onclick=()=>cambiarSeccion(b.dataset.section));document.querySelectorAll('[data-go]').forEach(b=>b.onclick=()=>cambiarSeccion(b.dataset.go));document.querySelectorAll('[data-close]').forEach(b=>b.onclick=()=>cerrar(b.dataset.close));document.querySelectorAll('.report-mode').forEach(b=>b.onclick=()=>setReportMode(b.dataset.reportMode));document.querySelectorAll('.strategy-mode').forEach(b=>b.onclick=()=>setStrategyMode(b.dataset.strategyMode));
  $('crmBtn').onclick=()=>irSegunRol('../CMR/crm.html');
  $('adminPanelBtn').onclick=()=>irSegunRol('../CMR/Administradores/admin.html');
  $('backBtn').onclick=()=>irSegunRol('../CMR/Administradores/admin.html','../pagPrin.html');
  $('themeBtn').onclick=toggleTheme;$('languageBtn').onclick=toggleLanguage;$('globalSearch').oninput=globalSearch;$('buscarProducto').oninput=renderProductos;$('filtroCategoria').onchange=renderProductos;$('buscarProveedor').oninput=renderProveedores;$('buscarInventario').oninput=renderInventario;$('filtroMovimientoTipo').onchange=cargarMovimientos;$('filtroMovimientoProducto').onchange=cargarMovimientos;$('filtroPedidoEstado').onchange=cargarPedidos;$('filtroPedidoTipo').onchange=cargarPedidos;
  $('nuevoProductoBtn').onclick=()=>{resetProducto();abrir('productoModal')};$('productoForm').onsubmit=guardarProducto;$('productoImagenArchivo').onchange=e=>{const f=e.target.files?.[0];if(!f)return;const url=URL.createObjectURL(f);$('productoImagenPreview').src=url;$('productoImagenPreview').onload=()=>URL.revokeObjectURL(url)};$('productosBody').onclick=e=>{const id=e.target.dataset.id;if(e.target.classList.contains('view-product'))verProducto(id);if(e.target.classList.contains('edit-product'))editarProducto(id);if(e.target.classList.contains('delete-product'))borrarProducto(id);if(e.target.classList.contains('strategy-product'))irAEstrategia(id)};
  $('nuevoProveedorBtn').onclick=()=>{$('proveedorForm').reset();$('proveedorId').value='';$('proveedorModalTitle').textContent='Nuevo proveedor';abrir('proveedorModal')};$('proveedorForm').onsubmit=guardarProveedor;$('proveedoresBody').onclick=e=>{const id=e.target.dataset.id;if(e.target.classList.contains('view-provider'))verProveedor(id);if(e.target.classList.contains('provider-course'))nuevoCursoParaProveedor(id);if(e.target.classList.contains('edit-provider'))editarProveedor(id);if(e.target.classList.contains('delete-provider'))borrarProveedor(id)};
  $('inventarioBody').onclick=e=>{const b=e.target.closest('.inv-history');if(b)verHistorialInventario(b.dataset.id)};$('movimientoDesdeHistorialBtn').onclick=()=>{if(!productoHistorialId)return;$('movimientoForm').reset();$('movimientoProducto').value=productoHistorialId;$('movimientoFecha').value=ahora();abrir('movimientoModal')};
  $('nuevoMovimientoBtn').onclick=()=>{$('movimientoForm').reset();$('movimientoFecha').value=ahora();abrir('movimientoModal')};$('movimientoForm').onsubmit=guardarMovimiento;
  $('estrategiaProducto').onchange=renderEstrategias;$('guardarEstrategiaBtn').onclick=guardarEstrategia;$('estrategiaBody').onclick=e=>{const b=e.target.closest('.strategy-row');if(b){$('estrategiaProducto').value=b.dataset.id;renderEstrategias();$('configurarEstrategiaPanel').scrollIntoView({behavior:'smooth'})}};
  $('nuevoPedidoBtn').onclick=()=>{$('pedidoForm').reset();$('pedidoFecha').value=ahora();abrir('pedidoModal')};$('pedidoForm').onsubmit=guardarPedido;$('pedidosBody').onchange=e=>{if(e.target.classList.contains('pedido-estado'))cambiarEstadoPedido(Number(e.target.dataset.id),e.target.value)};
  $('nivelScmRange').oninput=e=>pintarMadurez(e.target.value);$('guardarNivelBtn').onclick=guardarNivel;
  $('logoutBtn').onclick=async()=>{try{await api('logout.php',{method:'POST'})}finally{window.location.replace('../pagPrin.html')}};
  iniciar();
});
window.addEventListener('pageshow',()=>validarSesionAlVolver());
